image: python:3.6-alpine

stages:
  - deploy

before_script:
   - pip install twine
   - python setup.py sdist

deploy_PYPI:
  stage: deploy
  tags:
    - defaultjavarunner
  variables:
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  script:
    - twine upload dist/*
  only:
    - tags
